openapi: 3.0.1
info:
  version: 1.0.0
  title: EventReplayKafka
  description: En bakgrunnsprosess som puller Events fra EventStore og dytter dem på "clean"-kafka-topic.
paths:
  /isReady:
    get:
      tags:
        - diagnostics
      description: Readiness check.
      responses:
        '200':
          description: Service is ready.
  /isAlive:
    get:
      tags:
        - diagnostics
      description: Liveliness check.
      responses:
        '200':
          description: Service is alive.
  /prometheus:
    get:
      tags:
        - diagnostics
      description: Pull metrics.
      responses:
        '200':
          description: Metrics.
  /smokeTests/{name}:
    get:
      tags:
        - diagnostics
      description: Runs a smoke-test to verify an external integration.
      parameters:
        - name: name
          in: path
          description: Name of smoke-test.
          required: true
          schema:
            type: string
            enum: [eventStore]
      responses:
        '200':
          description: Ok.
        '500':
          description: Error.
