apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-fileshare
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  port: 8080
  team: helseopplysninger
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
      tenant: nav.no
  maskinporten:
    enabled: true
    scopes:
      exposes:
        - name: "helseopplysninger.read"
          enabled: true
          product: "helse"
          consumers:
            - name: "NAV"
              orgno: "889640782"
        - name: "helseopplysninger.write"
          enabled: true
          product: "helse"
          consumers:
            - name: "NAV"
              orgno: "889640782"
  gcp:
    buckets:
      - name: helse-hops-fileshare
      - name: helse-hops-fileshare-unscanned
        retentionPeriodDays: 1
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: LOG_APPENDER
      value: json
    - name: FILESTORE_BUCKET_NAME
      value: helse-hops-fileshare
    - name: FILESTORE_BUCKET_NAME_UNSCANNED
      value: helse-hops-fileshare-unscanned
    - name: FILESTORE_VIRUS_SCAN_ENABLED
      value: "true"
    - name: FILESTORE_REQUIRES_AUTH
      value: "true"
    - name: FILESTORE_TOKEN_FETCH_URL
      value: "http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token"
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
