services:
  hops-api_service:
    container_name: hops-api_container
    build: ./apps/hops-api
    restart: unless-stopped
    ports:
     - "8081:8080"
    networks:
      - hops_network

  hops-oppslag_service:
    container_name: hops-oppslag_container
    build: ./apps/hops-oppslag
    restart: unless-stopped
    ports:
     - "8082:8080"
    networks:
      - hops_network

  hapi_service:
    container_name: hapi_container
    image: hapiproject/hapi:latest
    restart: unless-stopped
    ports:
     - "8080:8080"
    networks:
      - hops_network
      - hapi-postgres_network
    volumes:
      - ./config:/etc/hopsconfig:ro
    environment:
      SPRING_CONFIG_LOCATION: 'file:///etc/hopsconfig/application.yaml'
   
  pgadmin_service:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.16
    restart: unless-stopped
    ports:
      - "5050:80"
    networks:
      - pgadmin-postgres_network
    volumes:
      - pgadmin_volume:/root/.pgadmin
      - ./config:/etc/hopsconfig:ro
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /etc/hopsconfig/servers.json
 
  postgres_service:
    container_name: postgres_container
    image: postgres:12.1
    restart: unless-stopped
    networks:
      - hapi-postgres_network
      - pgadmin-postgres_network
    volumes:
       - postgres_volume:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome01
      POSTGRES_DB: postgres
      PGDATA: /data/postgres

networks:
  hops_network:
  hapi-postgres_network:
  pgadmin-postgres_network:
 
volumes:
    postgres_volume:
    pgadmin_volume:
        