# See https://github.com/navikt/token-support#required-properties-yaml-or-properties
oauth:
  azure:
    name: azure
    discoveryUrl: ${AZURE_APP_WELL_KNOWN_URL:-http://mock-oauth2-service:8081/azure/.well-known/openid-configuration}
    audience: ${AZURE_APP_CLIENT_ID:-eventstore-audience}

# See https://doc.nais.io/persistence/postgres/#configuration
db:
  #url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  url: jdbc:postgresql://${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_DATABASE:-postgres}
  username: ${DB_USERNAME:-postgres}
  password: ${DB_PASSWORD:-Welcome01}
