apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-test-e2e
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  team: helseopplysninger
  liveness:
    path: /actuator/live
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /actuator/ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  replicas:
    min: 1
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "nav:helse:helseopplysninger.read"
        - name: "nav:helse:helseopplysninger.write"
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    outbound:
      rules:
        - application: hops-api
        - application: hops-event-replay-kafka
        - application: hops-event-sink-kafka
        - application: hops-event-store
  ingresses:
    - https://hops-test-e2e.ekstern.dev.nav.no/runTests
  env:
    - name: LOG_APPENDER
      value: json
    - name: API_HOST
      value: http://hops-api
    - name: API_HOST_EXTERNAL
      value: https://hops.dev.nav.no
    - name: EVENT_REPLAY_KAFKA_HOST
      value: http://hops-event-replay-kafka
    - name: EVENT_SINK_KAFKA_HOST
      value: http://hops-event-sink-kafka
    - name: EVENT_STORE_HOST
      value: http://hops-event-store
