openapi: 3.0.1
info:
  version: 1.0.0
  title: Archive
  description: En bakgrunnsprosess som lytter på 'rapid' kafka-topic og arkiverer meldinger i Joark.
paths:
  /actuator/ready:
    get:
      tags: [diagnostics]
      responses:
        '200':
          description: Service is ready.
  /actuator/alive:
    get:
      tags: [diagnostics]
      responses:
        '200':
          description: Service is alive.
  /actuator/metrics:
    get:
      tags: [diagnostics]
      responses:
        '200':
          description: Metrics.
