management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:helseopplysninger-db}
    username: ${DB_USERNAME:hops-hapi-fhir-server}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: false

  # See https://doc.nais.io/security/auth/azure-ad/#runtime-variables-credentials
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_OPENID_CONFIG_ISSUER}
          #The client_id of this application
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

hapi:
  fhir:
    fhir_version: R4