
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:helseopplysninger-db}
    username: ${DB_USERNAME:helseopplysninger-db}
    password: ${DB_PASSWORD:}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: ${HAPI_USERNAME:dev}
      password: ${HAPI_PASSWORD:dev}

  batch:
    job:
      enabled: false

hapi:
  fhir:
    fhir_version: R4