AAD_ISSUER_URI: https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}
ACCEPTED_AUDIENCE: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint:
    health.probes.enabled: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:helseopplysninger-db}
    username: ${DB_USERNAME:helseopplysninger-db}
    password: ${DB_PASSWORD:}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: false

  # See https://doc.nais.io/security/auth/azure-ad/#runtime-variables-credentials
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AAD_ISSUER_URI}/v2.0
          #The client_id of this application
          accepted-audience: ${ACCEPTED_AUDIENCE}

hapi:
  fhir:
    fhir_version: R4