spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:helseopplysninger-db}
    username: ${DB_USERNAME:helseopplysninger-db}
    password: ${DB_PASSWORD:}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: false

hapi:
  fhir:
    fhir_version: R4

# See https://github.com/navikt/token-support#required-properties-yaml-or-properties
# and https://doc.nais.io/security/auth/azure-ad/#runtime-variables-credentials
no.nav.security.jwt:
  issuer:
    azure:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}