version: "2.4"
services:
  github-api:
    image: mockserver/mockserver:mockserver-5.11.1
    command: -logLevel DEBUG -serverPort 443 -proxyRemotePort 80 -proxyRemoteHost https://api.github.com/
    ports: [ 1080:443 ]
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: true
      MOCKSERVER_INITIALIZATION_JSON_PATH: /etc/mock.json
    volumes:
      - ./mock.json:/etc/mock.json

