oauth:
  maskinporten:
    name: ${MASKINPORTEN_ISSUER_NAME:-maskinporten}
    discoveryUrl: ${MASKINPORTEN_WELL_KNOWN_URL:-http://mock-oauth2-service:8081/maskinporten/.well-known/openid-configuration}
    audience: ${HOPS_AUDIENCE:-helseopplysninger-audience}
    optionalClaims: "sub,nbf"
  publishScope: "nav:helse:helseopplysninger.write"
  subscribeScope: "nav:helse:helseopplysninger.read"

eventStore:
  baseUrl: ${HOPS_EVENTSTORE_BASE_URL:-http://localhost:8082}
  discoveryUrl: ${AZURE_APP_WELL_KNOWN_URL:-http://mock-oauth2-service:8081/azure/.well-known/openid-configuration}
  clientId: ${AZURE_APP_CLIENT_ID:-api-test-client-id}
  clientSecret: ${AZURE_APP_CLIENT_SECRET:-api-test-secret}
  scope: ${HOPS_EVENTSTORE_SCOPE:-eventstore}
