name: Auto merge PR

# ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
# │	  After a successful pull_request_target run, we will try to auto merge the pull-request.                         │
# │	  We will preserve this for dependabot only.                                                                      │                      │
# │	  We do not have to check for triggers by fork because the dependent workflow already do this.                    │
# ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

on:
  workflow_run:
    workflows: [ 'Pull request' ]
    types: [ completed ]
    branches:
      - 'dependabot/**'

jobs:
  # ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
  # │	Approve as CODEOWNER (bots cannot be codeowners, therefore we use a PAT)                                      │
  # │	Comment PR as the HOPS CI Tool bot                                                                            │
  # │	Merge PR as the HOPS CI Tool bot                                                                              │
  # ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
  dependabot-merge:
    name: 🤖 comment and merge
    runs-on: ubuntu-latest
    # Trigger if actor=dependabot and pull request was successful
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: ✅️ Approve as codeowner
        run: gh pr review $PR_BRANCH --approve
        env:
          GITHUB_TOKEN: ${{ secrets.CODEOWNER_PAT }}
          PR_BRANCH: ${{ github.event.workflow_run.head_branch }}
          GH_REPO: ${{ github.repository }}

      - name: 🔑 Generate team token
        uses: navikt/github-app-token-generator@v1
        id: gen-token
        with:
          private-key: ${{ secrets.HOPS_CI_TOOL_PRIVATE_KEY }}
          app-id: ${{ secrets.HOPS_CI_TOOL_APP_ID }}

      - name: 🎨️ Comment
        run: gh pr comment $PR_BRANCH --body "State is clean and mergable, will now squash this pull-request."
        env:
          GITHUB_TOKEN: ${{ steps.gen-token.outputs.token }}
          PR_BRANCH: ${{ github.event.workflow_run.head_branch }}
          GH_REPO: ${{ github.repository }}

      - name: 🧩️ Merge
        run: gh pr merge $PR_BRANCH --squash
        env:
          GITHUB_TOKEN: ${{ steps.gen-token.outputs.token }}
          PR_BRANCH: ${{ github.event.workflow_run.head_branch }}
          GH_REPO: ${{ github.repository }}

      - name: 🌍 Cache gradle dependencies
        uses: navikt/helseopplysninger/workflows/docker-build-image.yaml@main
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
