name: hops-api

on:
  push:
    branches: [main]
    paths:
      - 'apps/hops-api/**'
      - 'libs/**'
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'If the build should also be deployed to production (must be main branch.)'
        required: false
        default: 'false'
env:
  # Used by nais/deploy/actions/deploy, even though the documentation doesn't specify it.
  IMAGE: ghcr.io/navikt/${{ github.workflow }}:${{ github.sha }}

# The following jobs and steps can be moved to a common composite-action
# once GitHub support 'uses' in composite-actions: https://github.com/actions/runner/issues/646
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.4.0

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: project=${{ github.workflow }}
          push: true
          tags: ${{ env.IMAGE }},ghcr.io/navikt/${{ github.workflow }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_MANIFEST: apps/${{ github.workflow }}/.nais/naiserator.yaml
      ALERT_MANIFEST: apps/${{ github.workflow }}/.nais/alerts.yaml
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Deploy to Dev
        if: ${{ false }}
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/dev.json
          VAR: app=${{ github.workflow }},environment=dev
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: ${{ env.APP_MANIFEST }},${{ env.ALERT_MANIFEST }}

      - name: Run e2e tests
        run: bash .scripts/run-e2e

      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.deploy-prod == 'true'}}
        env:
          CLUSTER: prod-gcp
          ENVIRONMENT: prod-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/prod.json
          VAR: app=${{ github.workflow }},environment=prod
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: ${{ env.APP_MANIFEST }},${{ env.ALERT_MANIFEST }}
