openapi: 3.0.1
info:
  version: 1.0.0
  title: EventStore
  description: FHIR API for å lagre og hente FHIR-Messages.
paths:
  /isReady:
    get:
      tags:
        - diagnostics
      description: Readiness check.
      responses:
        '200':
          description: Service is ready.
  /isAlive:
    get:
      tags:
        - diagnostics
      description: Liveliness check.
      responses:
        '200':
          description: Service is alive.
  /prometheus:
    get:
      tags:
        - diagnostics
      description: Pull metrics.
      responses:
        '200':
          description: Metrics.
  /fhir/Bundle:
    get:
      tags:
        - FHIR
      description: Searches for FHIR Messages. https://www.hl7.org/fhir/messaging.html#rest
      parameters:
        - name: message.destination-uri
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Bundle of type SearchResult containing Bundles of type Message.
          content:
            application/fhir+json; fhirVersion=4.0:
              schema:
                type: object
  /fhir/$process-message:
    post:
      tags:
        - FHIR
      description: https://www.hl7.org/fhir/messageheader-operation-process-message.html
      requestBody:
        content:
          application/fhir+json; fhirVersion=4.0:
            schema:
              type: object
      responses:
        '202':
          description: Message has been determined valid and persisted in EventStore.
