name: 'Build and publish Docker image'
inputs:
  app:  # id of input
    required: true
runs:
  using: "composite"
  steps:
      env:
        IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ inputs.app }}:${{ github.sha }}
      run: |
        docker build --tag ${IMAGE} ./apps/${{ inputs.app }}
        docker login docker.pkg.github.com -u ${{ github.repository }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push ${IMAGE}