api:
  hops:
    api:
      host: ${API_HOST}
    eventreplaykafka:
      host: ${EVENTREPLAYKAFKA_HOST}
    eventsinkkafka:
      host: ${EVENTSINKKAFKA_HOST}
    eventstore:
      host: ${EVENTSTORE_HOST}
    fileshare:
      host: ${FILESHARE_HOST}
