ktor:
  #  development: true
  deployment:
    port: ${PORT:-8080}
    watch:
      - classes
      - resources
  application:
    modules:
      - e2e.AppKt.main

api:
  github:
    base-url: ${GITHUB_URL:-https://api.github.com}
  hops:
    api:
      host: ${API_HOST:-http://hops-api}
    eventreplaykafka:
      host: ${EVENTREPLAYKAFKA_HOST:-http://hops-eventreplaykafka}
    eventsinkkafka:
      host: ${EVENTSINKKAFKA_HOST:-http://hops-eventsinkkafka}
    eventstore:
      host: ${EVENTSTORE_HOST:-http://hops-eventstore}
    fileshare:
      host: ${FILESHARE_HOST:-http://hops-fileshare}
    test-external:
      host: ${TEST_EXTERNAL_HOST:-http://hops-test-external}
