apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-test-e2e
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  port: 8080
  team: helseopplysninger
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1
      memory: 3Gi
    requests:
      cpu: 500m
      memory: 3Gi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  env:
    - name: LOG_APPENDER
      value: json
