openapi: 3.0.1
info:
  version: 1.0.0
  title: FileShare
  description: Et api for å laste opp og ned binærfiler (bilder, video, pdf etc.) som inngår i FHIR meldinger som linker.
paths:
  /actuator/ready:
    get:
      tags: [diagnostics]
      responses:
        '200':
          description: Service is ready.
  /actuator/live:
    get:
      tags: [diagnostics]
      responses:
        '200':
          description: Service is alive.
  /actuator/metrics:
    get:
      tags: [diagnostics]
      responses:
        '200':
          description: Metrics.
