apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  name: hops-terminology
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  port: 8080
  team: helseopplysninger
  liveness:
    path: /fhir/ValueSet
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /fhir/ValueSet
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  env:
    - name: LOG_APPENDER
      value: json
    - name: SPRING_CONFIG_LOCATION
      value: "file:///data/hapi/application.yaml"
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
