apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-hapi-fhir-server
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: helseopplysninger-db
            envVarPrefix: DB
  liveness:
    path: /actuator/health/liveness
  readiness:
    path: /actuator/health/readiness
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
