apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-hapi-fhir-server
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  port: 8080
  team: helseopplysninger
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: helseopplysninger-db
            envVarPrefix: DB
  liveness:
    path: /actuator/health/liveness
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 900
  readiness:
    path: /actuator/health/readiness
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 900
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  azure:
    application:
      enabled: true
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
