apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hops-hapi-fhir-server
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: helseopplysninger-db
            envVarPrefix: DB
  liveness:
    path: /actuator/health/liveness
    initialDelay: 360
  readiness:
    path: /actuator/health/readiness
    initialDelay: 360
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: hops-api
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
