apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: bestilling
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  acl:
    - team: helseopplysninger
      application: hops-bestilling
      access: readwrite
    - team: helseopplysninger
      application: hops-hendelser
      access: readwrite
    - team: helseopplysninger
      application: hops-bestiller-backend
      access: readwrite
    - team: teamdigihot
      application: hm-fhir
      access: readwrite
    - team: teamdigihot
      application: digihot-kafka-debug
      access: read
