apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: rapid
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  pool: nav-prod
  acl:
    - team: helseopplysninger
      application: hops-event-sink-kafka
      access: read
    - team: helseopplysninger
      application: hops-behandler-backend
      access: write
    - team: helseopplysninger
      application: hops-bestiller-backend
      access: write
    - team: helseopplysninger
      application: sof-resource-puller
      access: write
