apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: rapid
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  pool: nav-prod
  acl:
    - application: event-sink-kafka
      access: read
