apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: river
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  pool: nav-prod
  acl:
    - team: helseopplysninger
      application: hops-event-replay-kafka
      access: readwrite
    - team: helseopplysninger
      application: hops-behandler-backend
      access: read
    - team: helseopplysninger
      application: hops-bestiller-backend
      access: read
