apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: river
  namespace: helseopplysninger
  labels:
    team: helseopplysninger
spec:
  pool: nav-dev
  acl:
    - team: helseopplysninger
      application: hops-event-replay-kafka
      access: readwrite
    - team: teamdigihot
      application: hm-fhir
      access: read
    - team: teamdigihot
      application: digihot-kafka-debug
      access: read
    - team: helseopplysninger
      application: hops-behandler-backend
      access: read
    - team: helseopplysninger
      application: hops-bestiller-backend
      access: read
    - team: helseopplysninger
      application: hops-test-e2e
      access: read
