name: Code Inspection

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '10 7 * * *'
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    name: Code Inspection
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.2-eap

  lisence:
    runs-on: ubuntu-latest
    name: License Autit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Qodana - License Audit
        uses: JetBrains/qodana-license-audit-action@v2.0-eap
