name: Code Inspection

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '10 7 * * *'
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    name: Code Inspection
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/cache@v2
        with:
          path: ~/work/_temp/_github_home/qodana-cache
          key: ${{ runner.os }}-qodana-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-qodana-${{ github.ref }}
            ${{ runner.os }}-qodana-
      - uses: JetBrains/qodana-action@v2.2.1-eap
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana

  lisence:
    runs-on: ubuntu-latest
    name: License Autit
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.5

      - name: Qodana - License Audit
        uses: JetBrains/qodana-license-audit-action@v2.0-eap

      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/qodana

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/qodana/report
          destination_dir: ./
