name: Code Inspection

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '10 7 * * *'
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    name: Code Inspection
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: JetBrains/qodana-action@v3.2.1
      - uses: actions/upload-artifact@v2
        with:
          name: code-inspection
          path: ${{ github.workspace }}/qodana

      - name: Upload to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ github.workspace }}/qodana/report/results/qodana.sarif.json

  lisence:
    runs-on: ubuntu-latest
    name: License Autit
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: JetBrains/qodana-license-audit-action@v2.0-eap
      - uses: actions/upload-artifact@v2
        with:
          name: license-audit
          path: ${{ github.workspace }}/qodana

      - name: Convert report.json to report.sarif
        run: |
          cp .scripts/licence-to-sarif.js ${{ github.workspace }}/qodana/licence-to-sarif.js
          node ${{ github.workspace }}/qodana/licence-to-sarif.js

      - name: Upload to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ github.workspace }}/qodana/report.sarif

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/qodana/report
          destination_dir: ./
