name: Detekt linting flaws

on:
  pull_request:
  push:
    branches:
      - fix/reviewdog
jobs:
  analyse:
    name: Static kotlin code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v2.3.4

      - name: detekt
        uses: natiginfo/action-detekt-all@1.18.0-RC3
        with:
          args: --fail-fast --report sarif:detekt.sarif

      - name: Upload report from linter
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: detekt.sarif