# Creates and publishes a Docker image containing a Gradle cache with all the required Maven dependencies.
name: Publish Docker build-image
on:
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.7.0
        with:
          file: .docker/builder/Dockerfile
          push: true
          tags: ghcr.io/navikt/hops-build:latest

  create-cache:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - uses: docker/setup-buildx-action@v1.6.0

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.7.0
        with:
          # NOTE: Can be any app, the point is to cache the navikt/hops-build and navikt/java images.
          build-args: project=hops-test-external
          cache-to: type=gha,scope=app,mode=max
