name: hops-api

on:
 push:
    branches:
      - '*'
    paths:
      - apps/${{ github.repository }}/**
      - .github/workflows/${{ github.workflow }}-feature.yaml

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.workflow }}:${{ github.sha }}

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.repository }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        context: ./apps/${{ github.workflow }}
        image_name: ${{ github.repository }}/${{ github.workflow }}
        image_tag: ${{ github.sha }}
    - name: Deploy to Dev
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: apps/${{ github.workflow }}/.nais/naiserator.yaml
        VARS: apps/${{ github.workflow }}/.nais/dev.json
    - name: Deploy to Prod
      if: github.ref == 'refs/heads/master'
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-gcp
        RESOURCE: apps/${{ github.workflow }}/.nais/naiserator.yaml
        VARS: apps/${{ github.workflow }}/.nais/prod.json