name: hops-api

on:
  push:
    branches: [main]
    paths:
      - 'apps/hops-api/**'
      - 'libs/**'
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'If the build should also be deployed to production (must be main branch.)'
        required: false
        default: 'false'
env:
  # Used by nais/deploy/actions/deploy, even though the documentation doesnt specify it.
  IMAGE: ghcr.io/navikt/${{ github.workflow }}:${{ github.sha }}

# The following jobs and steps can be moved to a common composite-action
# once github support 'uses' in composite-actions: https://github.com/actions/runner/issues/646
jobs:
  build-api:
    runs-on: ubuntu-latest
    env:
      BUILDX_CACHE_PATH: /tmp/.buildx-cache
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1.5.1

      - name: Set up Docker layers cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.BUILDX_CACHE_PATH }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache current image version
        run: |
          docker inspect ghcr.io/navikt/hops-api:latest \
            | jq .[0].Id -r \
            | awk '{print "fallback_image="$1}' \
            >> $GITHUB_ENV

      # debug
      - run: echo ${{ env.fallback_image }}

      - uses: docker/build-push-action@v2.7.0
        id: docker_build
        with:
          build-args: project=${{ github.workflow }}
          push: true
          tags: ${{ env.IMAGE }},ghcr.io/navikt/${{ github.workflow }}:latest
          cache-from: type=local,src=${{ env.BUILDX_CACHE_PATH }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_PATH }}-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf ${{ env.BUILDX_CACHE_PATH }}
          mv ${{ env.BUILDX_CACHE_PATH }}-new ${{ env.BUILDX_CACHE_PATH }}

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-api
    env: # Used by nais/deploy/actions/deploy. https://doc.nais.io/deployment/#action-configuration
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      RESOURCE: apps/${{ github.workflow }}/.nais/naiserator.yaml
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Deploy to Dev
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/dev.json

      # debug
      - run: echo ${{ env.fallback_image }}
      # debug
      - run: docker inspect ghcr.io/navikt/hops-api:latest | jq .[0].Id -r

      - name: Run e2e tests
        id: e2e
        run: |
          cat <<EOF >> e2e/hops-api.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <testsuite name="e2e.api" tests="1" skipped="0" failures="0" errors="0" timestamp="2021-08-30T13:39:11" hostname="dev" time="0.542">
          <testcase name="use case 1" classname="e2e.api" time="0.121"/>
          </testsuite>
          EOF
          exit 1
        continue-on-error: true
        timeout-minutes: 1 # fail fast

      - name: Publish results (e2e )
        if: steps.e2e.outcome == 'failure' && steps.e2e.conclusion == 'success'
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: e2e
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "e2e/hops-*.xml"

      # can we undo rollout on k8s or something?
      - name: Rollback if tests failed
        if: steps.e2e.outcome == 'failure' && steps.e2e.conclusion == 'success'
        run: "deploy previous version"
        uses: nais/deploy/actions/deploly@master
        env:
          IMAGE: ghcr.io/navikt/${{ github.workflow }}:${{ env.fallback_image }}
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/dev.json

      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.deploy-prod == 'true'}}
        env:
          CLUSTER: prod-gcp
          ENVIRONMENT: prod-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/prod.json
