name: hops-api-feature
 
on:
 push:
    branches:
      - '*'
    paths:
      - apps/hops-api/**
      - .github/workflows/hops-api-feature.yaml

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/hops-api:${{ github.sha }}

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: ${{ github.repository }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        context: ./apps/hops-api
        image_name: ${{ github.repository }}/hops-api
        image_tag: ${{ github.sha }}
    - name: Deploy to Dev
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: apps/hops-api/.nais/naiserator.yaml
        VARS: apps/hops-api/.nais/dev.json
    - name: Deploy to Prod
      if: github.ref == 'refs/heads/master'
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-gcp
        RESOURCE: apps/hops-api/.nais/naiserator.yaml
        VARS: apps/hops-api/.nais/prod.json