name: hops-api-feature
 
on:
 push:
    branches:
      - '*'
    paths:
      - apps/hops-api/**
      - .github/workflows/hops-api-feature.yaml

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/hops-api:${{ github.sha }}

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build-and-publish
      run: |
        docker build --tag ${IMAGE} ./apps/hops-api
        docker login docker.pkg.github.com -u ${{ github.repository }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push ${IMAGE}
    - name: Deploy to Dev
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: apps/hops-api/.nais/naiserator.yaml
        VARS: apps/hops-api/.nais/dev.json
    - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        if: github.ref == 'refs/heads/master'
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/hops-api/.nais/naiserator.yaml
          VARS: apps/hops-api/.nais/prod.json