name: hops-api

on:
  push:
    branches: [main, e2e]
    paths:
      - 'apps/hops-test-e2e/**'
      - 'libs/**'
env:
  IMAGE: ghcr.io/navikt/${{ github.workflow }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: project=${{ github.workflow }}
          push: true
          tags: ${{ env.IMAGE }},ghcr.io/navikt/${{ github.workflow }}:latest

  deploy_e2e:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy e2e to dev
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      RESOURCE: apps/${{ github.workflow }}/.config/nais.yml
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}
