name: hops-test-external

on:
  push:
    branches: [main]
    paths:
      - 'apps/hops-test-external/**'
      - 'libs/**'
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'If the build should also be deployed to production (must be main branch.)'
        required: false
        default: 'false'
env:
  # Used by nais/deploy/actions/deploy, even though the documentation doesnt specify it.
  IMAGE: ghcr.io/navikt/${{ github.workflow }}:${{ github.sha }}

# The following jobs and steps can be moved to a common composite-action
# once github support 'uses' in composite-actions: https://github.com/actions/runner/issues/646
jobs:
  build-test-external:
    runs-on: ubuntu-latest
    env:
      BUILDX_CACHE_PATH: /tmp/.buildx-cache
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/setup-buildx-action@v1.6.0

      - name: Set up Docker layers cache
        uses: actions/cache@v2.1.6
        with:
          path: ${{ env.BUILDX_CACHE_PATH }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.7.0
        id: docker_build
        with:
          build-args: project=${{ github.workflow }}
          push: true
          tags: ${{ env.IMAGE }},ghcr.io/navikt/${{ github.workflow }}:latest
          cache-from: type=local,src=${{ env.BUILDX_CACHE_PATH }}
          cache-to: type=local,dest=${{ env.BUILDX_CACHE_PATH }}-new

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf ${{ env.BUILDX_CACHE_PATH }}
          mv ${{ env.BUILDX_CACHE_PATH }}-new ${{ env.BUILDX_CACHE_PATH }}

  deploy-test-external:
    runs-on: ubuntu-latest
    needs: build-test-external
    env: # Used by nais/deploy/actions/deploy. https://doc.nais.io/deployment/#action-configuration
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      RESOURCE: apps/${{ github.workflow }}/.nais/naiserator.yaml
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Deploy to Dev
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/dev.json

      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.deploy-prod == 'true'}}
        env:
          CLUSTER: prod-gcp
          ENVIRONMENT: prod-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/prod.json
