name: hops-api-feature
 
on:
 push:
    branches:
      - '*'
      - '!master'
    paths:
      - apps/hops-api/**
      - .github/workflows/hops-api-feature.yaml

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/build-and-publish
      with:
        app: hops-api
    - name: Deploy to Dev
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: apps/hops-api/.nais/naiserator.yaml
        VARS: apps/hops-api/.nais/dev.json