name: hops-fileshare

on:
  push:
    branches: [main]
    paths:
      - 'apps/hops-terminology/**'
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'If the build should also be deployed to production (must be main branch.)'
        required: false
        default: 'false'

env:
  # Used by nais/deploy/actions/deploy, even though the documentation doesn't specify it.
  IMAGE: ghcr.io/navikt/${{ github.workflow }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.4

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build database files
        run: |
          cd apps/hops-terminology
          ./build.sh $(pwd)/data

      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: dataFolder=./data
          push: true
          tags: ${{ env.IMAGE }},ghcr.io/navikt/${{ github.workflow }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env: # Used by nais/deploy/actions/deploy. https://doc.nais.io/deployment/#action-configuration
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      RESOURCE: apps/${{ github.workflow }}/.nais/naiserator.yaml
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Deploy to Dev
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/dev.json

      - name: Run e2e tests
        run: bash .scripts/run-e2e
        # remove when e2e is stable
        continue-on-error: true

      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.deploy-prod == 'true'}}
        env:
          CLUSTER: prod-gcp
          ENVIRONMENT: prod-gcp:${{ github.workflow }}
          VARS: apps/${{ github.workflow }}/.nais/prod.json
