name: hops-maskinporten-client

on:
  push:
    branches: [main]
    paths: [apps/hops-api/.nais/maskinporten-client.yaml]
  workflow_dispatch:
    inputs:
      deploy-prod:
        description: 'If the client should also be deployed to production (must be main branch.)'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: # Used by nais/deploy/actions/deploy. https://doc.nais.io/deployment/#action-configuration
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
      RESOURCE: apps/hops-api/.nais/maskinporten-client.yaml
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Deploy to Dev
        uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}

      - name: Deploy to Prod
        uses: nais/deploy/actions/deploy@master
        if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.deploy-prod == 'true'}}
        env:
          CLUSTER: prod-gcp
          ENVIRONMENT: prod-gcp:${{ github.workflow }}
