name: hops-api-feature
 
on:
 push:
    branches:
      - '*'
      - '!master'
    paths:
      - apps/hops-api/**
      - .github/workflows/hops-api-feature.yaml
 
jobs:
 main:
   runs-on: ubuntu-latest
   steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./apps/hops-api
        tags: ${{ github.repository }}/hops-api:${{ github.sha }}