name: hops-api-poc

on:
#  pull_request:
  push:
    paths:
      - 'apps/hops-api/**'
      - 'libs/**'
env:
  IMAGE: ghcr.io/navikt/hops-api:${{ github.sha }}

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update and publish cached dependencies
        uses: docker/build-push-action@v2.7.0
        with:
          file: Dockerfile
          target: cache
          push: true
          build-args: BUILDKIT_INLINE_CACHE=1
          tags: ${{ env.IMAGE }},ghcr.io/navikt/hops-dependency-cache:latest
          cache-from: type=registry,ref=ghcr.io/navikt/hops-dependency-cache:latest

      - name: Build and publish app using cached dependencies
        uses: docker/build-push-action@v2.7.0
        with:
          file: Dockerfile
          target: app
          push: false
          build-args: |
            project=hops-api
            BUILDKIT_INLINE_CACHE=1
          tags: ${{ env.IMAGE }},ghcr.io/navikt/hops-api:latest
          cache-from: type=registry,ref=ghcr.io/navikt/hops-dependency-cache:latest
