name: hops-api-feature
 
on:
 push:
    branches:
      - '*'
      - '!master'
    paths:
      - apps/hops-api/**
      - .github/workflows/hops-api-feature.yaml

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/hops-api:${{ github.sha }}

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Build and publish Docker image
      run: |
        docker build --tag ${IMAGE} ./apps/hops-api
        docker login docker.pkg.github.com -u ${{ github.repository }} -p ${{ github.token }}
        docker push ${IMAGE}
    - name: Deploy to Dev
      uses: nais/deploy/actions/deploy@master
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: apps/hops-api/.nais/naiserator.yaml
        VARS: apps/hops-api/.nais/dev.json