name: hops-test-e2e

on:
  push:
    branches:
      - 'apps/hops-test-external/**'
      - 'e2e/**'
    paths:
      - 'apps/hops-test-e2e/**'
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/${{ github.workflow }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.5
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: project=${{ github.workflow }}
          push: true
          tags: ${{ env.IMAGE }},ghcr.io/navikt/${{ github.workflow }}:latest

  deploy_e2e:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy e2e to dev
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: dev-gcp
          ENVIRONMENT: dev-gcp:${{ github.workflow }}
          RESOURCE: apps/${{ github.workflow }}/.nais/naiserator.yaml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

      - name: Run e2e tests
        run: bash .scripts/run-e2e
