name: hops-api-feature
 
on:
 push:
    branches:
      - '*'
      - '!master'
    paths:
      - apps/hops-api/**
      - .github/workflows/hops-api-feature.yaml
env:
  CACHE_PATH: /tmp/.buildx-cache

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ${CACHE_PATH}
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository }}
        password: ${{ github.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ./apps/hops-api
        tags: docker.pkg.github.com/${{ github.repository }}/hops-api:${{ github.sha }}
        cache-from: type=local,src=${CACHE_PATH}
        cache-to: type=local,dest=${CACHE_PATH}