name: Static code analysis

on: [ pull_request ]
  # https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v2.3.4

      - name: Get latest ktlint download-url
        id: ktlint-latest
        # Reference: https://github.com/ScaCap/action-ktlint/blob/master/Dockerfile
        run: |
          echo "::set-output name=DOWNLOAD_URL::$( \
          curl -SSL https://api.github.com/repos/pinterest/ktlint/releases/latest \
          | grep "browser_download_url.*ktlint\"" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          )"

      - name: ktlint cache
        uses: actions/cache@v2.1.6
        id: ktlint-cache
        with:
          path: ktlint
          key: ${{ runner.os }}-${{ steps.ktlint-latest.outputs.DOWNLOAD_URL }}

      - name: Download newest ktlint
        if: steps.ktlint-cache.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.ktlint-latest.outputs.DOWNLOAD_URL }} | wget -qi -
          chmod a+x ktlint

      - name: run ktlint
        run: ./ktlint --relative --reporter=checkstyle,output=build/ktlint-report.xml

      - name: print ktlint results
        if: always()
        run: cat build/ktlint-report.xml

      - name: Upload Ktlint Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Ktlint-results
          path: 'build/ktlint-report.xml'
          retention-days: 5
