on:
  push:
    branches: [main]
    paths:
      - 'libs/**'
      - '!libs/*/test/**'

jobs:
  build-dependents:
    runs-on: ubuntu-latest
    jobs:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'gradle'