# https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
name: Static code analysis

on: [ pull_request ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    name: Run ktlint
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v2.3.4

      - name: Get latest ktlint download url
        id: ktlint-latest
        run: |
          echo "::set-output name=KTLINT_URL::$( \
            curl -SSL https://api.github.com/repos/pinterest/ktlint/releases/latest \
            | jq .assets[0] | jq .browser_download_url -r \
          )"

      - name: Use cache
        uses: actions/cache@v2.1.6
        id: ktlint-cache
        with:
          path: ktlint
          key: ${{ runner.os }}-${{ steps.ktlint-latest.outputs.KTLINT_URL }}

      - name: Download newest ktlint
        if: steps.ktlint-cache.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.ktlint-latest.outputs.DOWNLOAD_URL }} | wget -qi -
          chmod a+x ktlint

      - name: run ktlint
        run: ./ktlint --relative --reporter=checkstyle,output=build/ktlint-report.xml

      - name: print ktlint results
        if: always()
        run: cat build/ktlint-report.xml

      - name: Upload Ktlint Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Ktlint-results
          path: 'build/ktlint-report.xml'
          retention-days: 5
