name: Dependabot's Pull Request

on: pull_request

jobs:
  test-unit:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'
          cache: 'gradle'

      - run: gradle test --no-daemon
