# See https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches
name: pull-request-report
on:
  workflow_run:
    workflows: [pull-request] # name of the workflow to trigger on.
    types: [completed]

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: pull-request
          run_id: ${{ github.event.workflow_run.id }}
      - uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: "**/build/test-results/test/TEST-*.xml"
      - uses: reviewdog/action-setup@v1
      - name: Publish ktlint results
        if: always() # Should be published regardless of failing unit-tests.
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_PULL_REQUEST: ${{ github.event.workflow_run.pull_requests[0].number }}
          CI_COMMIT: ${{ github.event.workflow_run.head_sha }}
        run: |
          cat Ktlint-results/ktlint-report-in-checkstyle-format.xml \
          | reviewdog -f=checkstyle -name=ktlint -reporter=github-pr-check
