name: reviewdog
on:
  pull_request:
    branches:
      - main

jobs:
  ktlint: # https://github.com/ScaCap/action-ktlint
    name: Check coding style violations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ktlint
        uses: ScaCap/action-ktlint@1.3
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
          level: warning
  detekt: # https://github.com/alaegin/Detekt-Action
    name: Code smell analysis
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: detekt
        uses: DominuS-RU/Detekt-Action@v1.16.0
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt-config.yml
          fail_on_error: true
          reviewdog_level: warning
