name: reviewdog
on:
  pull_request:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/ScaCap/action-ktlint
      - uses: ScaCap/action-ktlint@1.3
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
      # https://github.com/alaegin/Detekt-Action
      - uses: DominuS-RU/Detekt-Action@v1.16.0
        with:
          github_token: ${{ secrets.github_token }}
          detekt_config: detekt-config.yml
          fail_on_error: true
          reviewdog_level: warning
          detekt_excludes: '**/build/**,**/.idea/**",**/test/**'
