name: Reviewdog

on:
  pull_request:
  push:
    branches:
      - fix/reviewdog

jobs:
  code-violations:
    name: Review Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v2.3.4

      - name: Run linter
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review