name: Security

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    name: Vulnerability scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run vulnerability scan
        uses: snyk/actions/gradle-jdk16@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --all-sub-projects --configuration-matching='^runtimeClasspath'

      # This is a temporary manual fix while waiting for https://github.com/snyk/actions/issues/66
      - name: Remove prefix /github/workspace/ from file paths
        run: |
          jq \
            < snyk.sarif \
            '.runs[].results[].locations[].physicalLocation.artifactLocation.uri |= sub("/github/workspace/";"")' \
            > snyk_modified.sarif

      - name: Upload result to GitHub Code Scanning
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v1
        with:
#          sarif_file: snyk.sarif
          sarif_file: snyk_modified.sarif

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          path: |
            snyk.sarif
            snyk_modified.sarif
