name: Test

on: [ pull_request ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'

      # Must login to gain access to docker.pkg.github.com/navikt/* images required by some integration-tests.
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: ./gradlew test --continue
        continue-on-error: true # enable for uploading failing tests

      - name: Upload Unit Test Results
        if: always() # Publish the results, even if there are failing tests.
        uses: actions/upload-artifact@v2
        with:
          name: Test-results
          path: '**/build/test-results/test/TEST-*.xml'
          retention-days: 5

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
